version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: training
      POSTGRES_PASSWORD: training
      POSTGRES_DB: training
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage

  minio:
    image: minio/minio:RELEASE.2024-06-04T19-20-08Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  backend:
    build:
      context: ../backend
    environment:
      SECRET_KEY: super-secret-key
      POSTGRES_DSN: postgresql+psycopg://training:training@postgres:5432/training
      S3_ENDPOINT_URL: http://localhost:9001
      S3_BUCKET_NAME: training-videos
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      VECTOR_STORE_URL: http://localhost:6333
      VECTOR_COLLECTION_NAME: video_transcripts
      EMBEDDING_MODEL: text-embedding-3-small
      EMBEDDING_DIMENSION: 64
      OPENAI_API_KEY: ""
      AGORA_APP_ID: ""
      AGORA_API_KEY: ""
      CORS_ORIGINS: '["http://localhost:5173","http://frontend"]'
    depends_on:
      - postgres
      - qdrant
      - minio
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app/app
      - ../backend/alembic:/app/alembic
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ../frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres-data:
  qdrant-data:
  minio-data:
